# Generated by Django 2.1.3 on 2018-12-09 19:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import kernel.utils.upload_to
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_MAINTAINER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=127)),
                ('homepage', models.URLField(blank=True)),
                ('acronym', models.CharField(blank=True, max_length=63)),
                ('description', models.TextField()),
                ('medium_slug', models.CharField(blank=True, max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintainerInformation',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(primary_key=True, serialize=False)),
                ('short_biography', models.TextField(max_length=255)),
                ('normie_image', models.ImageField(upload_to=kernel.utils.upload_to.UploadTo('maintainer_site', 'normie_image'))),
                ('dank_image', models.ImageField(upload_to=kernel.utils.upload_to.UploadTo('maintainer_site', 'dank_image'))),
                ('favourite_music', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('favourite_literature', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('favourite_video', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('favourite_hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('technical_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('favourite_games', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=63), size=5)),
                ('maintainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_MAINTAINER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'maintainer information',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127, unique=True)),
                ('short_description', models.TextField(blank=True, max_length=255)),
                ('long_description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to=kernel.utils.upload_to.UploadTo('maintainer_site', 'projects'))),
                ('members', models.ManyToManyField(to=settings.KERNEL_MAINTAINER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
