# Generated by Django 2.1.3 on 2018-11-27 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kernel.utils.upload_to
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_MAINTAINER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('short_description', models.TextField(blank=True, max_length=255)),
                ('long_description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to=kernel.utils.upload_to.UploadTo('maintainer_site', 'projects'))),
                ('url', models.URLField(null=True)),
                ('members', models.ManyToManyField(to=settings.KERNEL_MAINTAINER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
