# Generated by Django 2.2 on 2019-05-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('maintainer_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maintainer_site.MaintainerInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
