# Generated by Django 4.1.5 on 2023-05-28 11:50

from django.db import migrations, models
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0002_hit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintainerinformation',
            old_name='handle',
            new_name='informal_handle',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='dank_image',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='normie_image',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='short_biography',
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='childhood_image',
            field=models.ImageField(null=True, upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'informal_image')),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='favourite_series',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='favourite_sports',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='formal_biography',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='formal_image',
            field=models.ImageField(null=True, upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'formal_image')),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='informal_biography',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='personality_type',
            field=models.SlugField(null=True),
        ),
    ]
