# Generated by Django 4.1.5 on 2025-06-20 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0002_hit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(choices=[('misc', 'Miscellaneous'), ('photoshoot', 'Photoshoot'), ('chaapo', 'Chaapo'), ('winter_trip', 'Winter Trip'), ('festival', 'Festival'), ('farewell', 'Farewell')], default='misc', max_length=63)),
                ('cover_image', models.ImageField(upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'culture'))),
            ],
            options={
                'verbose_name_plural': 'culture memories',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_anime_lover',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is an anime lover'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_cinematographer',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a cinematographer'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_cricket_lover',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a cricket lover'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_early_bird',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is an early bird'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_foodie',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a foodie'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_gamer',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a gamer'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_mac_user',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a Mac user'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_night_owl',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a night owl'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_singer',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a singer'),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='is_windows_user',
            field=models.BooleanField(default=False, help_text='Whether the maintainer is a Windows user'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether the project is featured on the maintainer site'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='', upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'project_logo')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='time_published',
            field=models.DateField(default=datetime.datetime(2025, 6, 20, 19, 7, 56, 652995, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'project_image')),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'culture_albums'))),
                ('drive_link', models.URLField(help_text='Link to the Google Drive folder containing the album photos')),
                ('year', models.PositiveIntegerField(help_text='Year to which the album belongs')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='maintainer_site.culture')),
            ],
            options={
                'verbose_name_plural': 'Culture albums',
            },
        ),
    ]
