# Generated by Django 4.1.5 on 2025-06-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0003_culture_alter_project_options_remove_project_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='is_early_bird',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='is_foodie',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='is_mac_user',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='is_night_owl',
        ),
        migrations.RemoveField(
            model_name='maintainerinformation',
            name='is_windows_user',
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='os_preferences',
            field=models.CharField(blank=True, help_text='Comma-separated list of OS preferences (windows, mac, linux)', max_length=255),
        ),
    ]
