# Generated by Django 4.1.5 on 2023-10-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import formula_one.utils.upload_to


class Migration(migrations.Migration):

    replaces = [('maintainer_site', '0004_blog'), ('maintainer_site', '0005_rename_link_blog_url'), ('maintainer_site', '0006_rename_guid_blog_id'), ('maintainer_site', '0007_rename_id_blog_guid'), ('maintainer_site', '0008_maintainerinformation_nick_name_and_more'), ('maintainer_site', '0009_maintainerinformation_want_to_be'), ('maintainer_site', '0010_alter_maintainerinformation_personality_type'), ('maintainer_site', '0011_alter_maintainerinformation_want_to_be'), ('maintainer_site', '0012_alter_maintainerinformation_want_to_be')]

    dependencies = [
        ('maintainer_site', '0003_rename_handle_maintainerinformation_informal_handle_and_more'),
        ('shell', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('guid', models.SlugField(max_length=127, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('display_image', models.ImageField(upload_to=formula_one.utils.upload_to.UploadTo('maintainer_site', 'blogs'))),
                ('read_time', models.IntegerField()),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.KERNEL_MAINTAINER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='nick_name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintainerinformation',
            name='personality_type',
            field=models.CharField(choices=[('adventurer', 'Adventurer'), ('advocate', 'Advocate'), ('architect', 'Architect'), ('campaigner', 'Campaigner'), ('commander', 'Commander'), ('consul', 'Consul'), ('debater', 'Debater'), ('defender', 'Defender'), ('entertainer', 'Entertainer'), ('entrepreneur', 'Entrepreneur'), ('executive', 'Executive'), ('logician', 'Logician'), ('logistician', 'Logistician'), ('mediator', 'Mediator'), ('protagonist', 'Protagonist'), ('virtuoso', 'Virtuoso')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintainerinformation',
            name='personality_type',
            field=models.CharField(choices=[('adventurer', 'Adventurer'), ('advocate', 'Advocate'), ('architect', 'Architect'), ('campaigner', 'Campaigner'), ('commander', 'Commander'), ('consul', 'Consul'), ('debater', 'Debater'), ('defender', 'Defender'), ('entertainer', 'Entertainer'), ('entrepreneur', 'Entrepreneur'), ('executive', 'Executive'), ('logician', 'Logician'), ('logistician', 'Logistician'), ('mediator', 'Mediator'), ('protagonist', 'Protagonist'), ('vistuoso', 'Vistuoso')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintainerinformation',
            name='want_to_be',
            field=models.TextField(max_length=127, null=True),
        ),
    ]
