# Generated by Django 4.1.5 on 2025-08-05 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_MAINTAINER_MODEL),
        ('maintainer_site', '0005_project_id_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_maintainer', to=settings.KERNEL_MAINTAINER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_maintainers', to='maintainer_site.project')),
            ],
            options={
                'verbose_name_plural': 'project_maintainers',
                'unique_together': {('project', 'maintainer')},
            },
        ),
    ]
