# Generated by Django 4.1.5 on 2025-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0006_projectmaintainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaintainer',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
