# Generated by Django 4.1.5 on 2025-08-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintainer_site', '0007_alter_projectmaintainer_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmaintainer',
            options={'verbose_name_plural': 'project maintainers'},
        ),
    ]
